const projekte = [
  {
    id: 0,
    status: "In Arbeit",
    titel: "&lt;Fabi.Dev&gt;",
    description: "Meine eigene Lern- und Projektseite.",
    tags: ["HTML", "CSS", "JavaScript"],
    backTitle: "Was steckt drin?",
    backText: "Dieses Portfolio ist meine Lernseite. Hier zeige ich Projekte, JavaScript-Uebungen und meinen Fortschritt als Entwickler.",
    number: "01",
  },
  {
    id: 1,
    status: "In Arbeit",
    titel: "JavaScript Uebungen",
    description: "Uebungen zur Verbesserung meiner JavaScript-Faehigkeiten.",
    tags: ["JavaScript", "DOM", "Events"],
    backTitle: "Was steckt drin?",
    backText: "Hier sammle ich kleine JavaScript-Features wie Filter, Buttons, Karten, Interaktionen und spaeter API-Tests.",
    number: "02",
  },
  {
    id: 2,
    status: "Pausiert",
    titel: "Test Webseite",
    description: "Ein Testprojekt zur Demonstration meiner Faehigkeiten.",
    tags: ["HTML", "CSS", "JavaScript"],
    backTitle: "Was steckt drin?",
    backText: "Diese Testseite dient dazu, meine Faehigkeiten in HTML, CSS und JavaScript zu demonstrieren.",
    number: "03",
  },
];
